### ISSUE TITLE
RP inventory

### ISSUE THREAD

**Issue by innuk** [kajisensei/Total-RP-3-Extended#18]
I have enjoyed the TRP3 system so far, and have the TRP3-E installed as well.  The trouble is there is no information on how to use the RP inventory, no FAQ exists on it, nor any troubleshooting to search for in regards to the RP inventory.   The trouble is, I open it, can see the "default bag", even open a frame for the rp inventory, but I cannot put anything in it (by dragging and dropping),  the slots do not accept anything(the item does not show up in the RP inventory), and the "default bag" seems to appear only for show, as nothing can be deposited into it, nor does it co-relate to any bags I have in my character's posession.  
If I have missed something, I hope I can be set straight, or possibly be pointed to some documentation released to explain unlocking the RP inventory bag.

**Comment by Solanya** [comment]
Hi ! There is a video available on the official Youtube channel explaining the basics of Extended inventory : https://www.youtube.com/watch?v=QouuCvC_Y6M

From what I gathered, you were trying to put "real" game objects into your RP inventory, which isn't how Extended works. The Extended inventory can only contain Extended items that have been created through the database (you can access it using the icon with a gnome gizmo called "Extended objects database").

The best way to get acquainted with the database is using the small "i" buttons on most windows (like the one at the bottom of the main database window) and trying out item creation using the Quick Item editor at first (Create item > Quick creation).

Feel free to ask if you have any more questions :)

**Comment by innuk** [comment]
Yes, that was correct.  I was trying to put "real" objects into it.  Thanks for the link to the Video.  I did find it very helpful.
